### PR TITLE
ci(infracost): adding infracost action to reusable workflow

### PR DESCRIPTION
**Pull request by Divyesh85**
# Description

# Motivation and Context

Adding infracost api check to create cost awareness
# How Has This Been Tested?

This was tested at the pr - https://github.com/Nmbrs/tf-services/pull/177
# Screenshots
image

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by fargozhu — COMMENTED** [review]
@Divyesh85 I think this could be more useful on the provisioning workflow, since it's where the product owner or whoever is responsible for would check it out. Also, keeping here it will be trigger multiple times creating a lot of noise on the PR conversation thread.

**Comment by filipefigueredo** [comment]
@fargozhu:

1) This implementation is based on the fact that we do comments in the PR, as can be seen in this snippet:
```bash
$infracost comment github --path /tmp/infracost.json \
   --repo $GITHUB_REPOSITORY \
   --github-token ${{github.token}} \
   --pull-request ${{github.event.pull_request.number}} \
   --behavior update 
```
To make it available in the provision PR we need to post it somewhere else, for example in a slack channel(https://www.infracost.io/docs/integrations/slack/) or at the issues section (in this we need to use github scripts action probably).

Do we want it?



2) Infracost always updates the same comment as you can in this comment : https://github.com/Nmbrs/tf-services/pull/177#issuecomment-1112310838 (check the updates in the *edit* button)

**Comment by filipefigueredo** [comment]
@fargozhu

As we discussed before, Infracosts steps shall be optional, correct?

**Comment by filipefigueredo** [comment]
> @Divyesh85 I think this could be more useful on the provisioning workflow, since it's where the product owner or whoever is responsible for would check it out. Also, keeping here it will be trigger multiple times creating a lot of noise on the PR conversation thread.

@fargozhu:

1) This implementation is based on the fact that we do comments in the PR, as can be seen in this snippet:
```bash
$infracost comment github --path /tmp/infracost.json \
   --repo $GITHUB_REPOSITORY \
   --github-token ${{github.token}} \
   --pull-request ${{github.event.pull_request.number}} \
   --behavior update 
```
To make it available in the provision PR we need to post it somewhere else, for example in a slack channel(https://www.infracost.io/docs/integrations/slack/) or at the issues section (in this we need to use github scripts action probably).

Do we want it?



2) Infracost always updates the same comment as you can in this comment : https://github.com/Nmbrs/tf-services/pull/177#issuecomment-1112310838 (check the updates in the *edit* button)

**Comment by fargozhu** [comment]
@filipefigueredo I think it should comment on the pull request, but not on every committee. That's why I was a suggesting to have the infracost step on the provision reusable workflow instead, since it will only run once - when merging to the main.

**Comment by Divyesh85** [comment]
@fargozhu as @filipefigueredo mentioned it will not post comment multiple times but only once, it just updates that comment for each commit if there are any changes, if no changes nothing new is being added so it will not create additional noise for the PR, also since after every change user can view the implication regarding the costs so i think that would help him make good choices.

**Review by fargozhu — APPROVED** [review]

**Pull request merged**
